### ISSUE TITLE
Cannot receive any new message after startup

### ISSUE THREAD

**Issue by tmvkrpxl0** [jeonghanlee/kakaotalk-env#8]
**Describe the bug**

Cannot receive any new message after startup

**To Reproduce**

1. Start kakaotalk
2. Send message to yourself

**Expected behavior**
I should get message from myself, but i don't see message from myself and it says my message is still being sent
**Screenshots**
![image](https://user-images.githubusercontent.com/41675181/113509810-7e337f00-9592-11eb-8d65-f12081462b6f.png)
![Screenshot_20210404-220836_KakaoTalk](https://user-images.githubusercontent.com/41675181/113509905-f732d680-9592-11eb-86a3-e3988f337f83.png)

**Desktop (please complete the following information):**

- OS: Linux mint Cinnamon Edition
- Kernel Version 5.11.11-xanmod1
- Wine version: 6.0

**Comment by jeonghanlee** [comment]
I've tested the latest Mint with the following information

```bash
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```

And its kernel version is 
```bash
Linux jhlee-VirtualBox 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I don't see any issues with the communication at all. My suspicion remains your kernel version, because of RT kernel possibilities even if the kernel itself which you used isn't RT.  

If this is the case, the following paragraphs could be valid. If not, I want to ask you to revert your kernel to the Mint default and then check whether a similar issue remains or not. 


_Since RT has a different way to handle all processes, I cannot say how it cooperates with the wine and kakaotalk. I don't think the Kakaotalk application is for the RT requirement at all._ 

_If you must use that kernel with the wine emulated Kakaotalk, you should study how RT works with wine, and kakaotalk in terms of its processes, interrupt (irqbalance service), and network communication within your specific kernel and RT configuration as well._

_My RT system doesn't have any other application except the critical application for its specific tasks. I don't have any graphical interface at all. Thus, I cannot help you to figure out them either._ 


HTH,
@jeonghanlee

**Comment by tmvkrpxl0** [comment]
The kernel i'm using is not Real-Time kernel. Also, i was able to receive new message sometimes, but it mostly doesn't work.
I suggest you to test it with other people, since it seems that sending message to yourself works better than sending to other people.
If you still haven't experienced the issue, try re-starting kakaotalk process entirely and try sending message again. you should experience this issue in 5 attempts

**Comment by jeonghanlee** [comment]
@tmvkrpxl0 Sorry about your issue.  But that is all I can do. It **works well** with minor communication issues always of Kakaotalk with Debian 10 so far (I saw this issue even I used Mac Kakaotalk also.) 

Please understand this repository's purpose, I don't work for Kakaotalk, wine has limited functionalities, and I am not the developer for the wine either. 

It is your turn to debug this if you want to fix it. If you want to do, please consult `winedbg` command as well. I don't have time to debug your communication issues. I am really sorry about this.

**Comment by jeonghanlee** [comment]
@tmvkrpxl0 Sorry about your issue, but I don't have the Mint system at all, I spent 2 hours setting up the Mint VM, because I have limited resources of my Debian machine, saw no issue. I see from time to time the communication issue on Debian 10 / Mac Big Sur as well. Sometimes, I force to restart the Kakaotalk by using the script, because it doesn't work at all. And mostly time, it works again without any issue. 

And with limited information, I can only see you have a different kernel version that isn't the same as the default Mint kernel. This is the reason of my previous suggestion. 

And please understand this repository's purpose, this is the configuration environment (only scripts, makefile I have here), not the Kakaotalk itself. This isn't the Linux distribution of the Kakaotalk.

I don't work for Kakao, don't work for Wine either. So that is all I can help you. I am going to close this issue later. 


HTH,
@jeonghanlee

**Comment by tmvkrpxl0** [comment]
I see, i'll close this issue now. For me, Kakaotalk installed with this repository worked the best, any other attempts *always* had some issues. this one at least works sometimes
